on:
  schedule:
    # Runs every hour, only in September through December and January through February
    - cron:  '0 0/1 * 9-12,1-2 *'
  workflow_dispatch:

name: Release Practice Reports

jobs:
  release_reports:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v7
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           packages: logger, nflverse/nflapi, nflverse/nflverse-data
           dependencies: '"hard"'

      - name: Run release script
        run: |
          release_practice_reports <- function(season){
            logger::log_separator()
            logger::log_info("Release {season} practice reports")
            logger::log_separator()
            injuries <- nflapi:::.nflapi_injuries_with_practice_days(season = season)
            nflversedata::nflverse_save(
              injuries,
              paste0("injuries_", season),
              "Injury Data",
              "nfl-injuries",
              file_types = c("rds", "parquet"),
              repo = "mrcaseb/nfl-data"
            )
            logger::log_success("DONE")
          }
          release_practice_reports(season = nflreadr::most_recent_season(roster = TRUE))
        shell: Rscript {0}
